### PR TITLE
800-Update-serial-reset-sql

### PR DESCRIPTION
**Pull request by andreievg**
closes: #800 

Description as per comments

### CODE REVIEW

**Comment by andreievg** [comment]
This PR also updates version of pg-diff-cli to 2.4, which is in latest build branch, we wanted `COMMENT ON` statements to persist for postgraphile.

**Comment by CarlosNZ** [comment]
Hi @andreievg, thanks for this, but I can't get it to work.

I downloaded latest snapshot from 50000 instance, which has been having problems with the `organisation_application_join` table and the `data_table_product` table, amongst others.

I copied and pasted and ran this script as per your PR:
```
SELECT 'SELECT SETVAL(' || quote_literal(sequence_number.relname) || ', COALESCE(MAX(' || quote_ident(table_and_column.column_name) || '), 1)) FROM ' || quote_ident(table_and_column.table_name) || ';'
FROM information_schema.columns AS table_and_column
JOIN pg_class AS sequence_number ON table_and_column.column_default LIKE 'nextval(' || quote_literal(sequence_number.relname) || '::regclass)'
WHERE sequence_number.relkind = 'S'
ORDER BY table_and_column.table_name
```

And it appear to run okay. But when I try and manually add records to those tables (without specifying the id), I still get the same error, e.g.
```
ERROR:  duplicate key value violates unique constraint "organisation_application_join_pkey"
DETAIL:  Key (id)=(3) already exists.
```

**Comment by andreievg** [comment]
@CarlosNZ did you run the script that this script generates ? (i.e. the script is meant to generate SQL script, [this .sh](https://github.com/openmsupply/conforma-server/blob/develop/database/update_serials.sh) saves generated script in temp file and runs it, useSnapshot runs that `.sh`)

**Review by CarlosNZ — APPROVED** [review]
Okay, I tested as part of a snapshot restore, and it seems to work nicely. Thanks for sorting that.

One thing I don't quite understand -- when I run that script manually in SQL, all it does is *generate* a bunch of statements such as `SELECT SETVAL('data_table_product_id_seq', COALESCE(MAX(id), 1)) FROM data_table_product;`, but it doesn't actually *run* them, so the serial reset hasn't occurred. I can run each statement manually and it works though.

So how does this script get fully executed when called as part of the snapshot script?

**Comment by CarlosNZ** [comment]
> @CarlosNZ did you run the script that this script generates ? (i.e. the script is meant to generate SQL script, [this .sh](https://github.com/openmsupply/conforma-server/blob/develop/database/update_serials.sh) saves generated script in temp file and runs it, useSnapshot runs that `.sh`)

Ha ha timing -- looks like you answered my question at the exact time I just asked it. Nice :)

**Pull request merged**
