### PR TITLE
Add new function to check for all approved/agreed

### PR DESCRIPTION
**Pull request by nmadruga**
Please check more info in: [Front-end PR](https://github.com/openmsupply/conforma-web-app/pull/1391)

Based on PR (Refactoring for `migrationData`) #914 

### Changes

Adds function to be used in comparison to check if Review (going to be submitted) has all APPROVED/AGREED elements that should be for All Reviews - even if there are other ones involved - for elements which are **reviewable**...

The Condition on IncrementStage now is a bit complex, but I couldn't  figure out how to make a simpler function that could check one against the other. If anyone knows, please add to here, and then we can have a single-graphQL call to check : )

IncrementStage Condition:
```json
{
 "operator": "AND",
 "children": [
  {
   "operator": "OR",
   "children": [
    {
     "operator": "AND",
     "children": [
      {
       "operator": "=",
       "children": [
        {
         "operator": "objectProperties",
         "children": [
          "applicationData.reviewData.latestDecision.decision"
         ]
        },
        "CONFORM"
       ]
      },
      {
       "operator": "=",
       "children": [
        {
         "operator": "graphQL",
         "children": [
          "query approvedAssignedQuestionsCount(\n  $appId: Int!\n  $stageId: Int!\n  $levelNumber: Int!\n) {\n  approvedAssignedQuestionsCount(\n    appId: $appId\n    stageId: $stageId\n    levelNumber: $levelNumber\n  )\n}",
          "graphqlendpoint",
          [
           "appId",
           "stageId",
           "levelNumber"
          ],
          {
           "operator": "objectProperties",
           "children": [
            "applicationData.applicationId",
            null
           ]
          },
          {
           "operator": "objectProperties",
           "children": [
            "applicationData.stageId",
            null
           ]
          },
          {
           "operator": "objectProperties",
           "children": [
            "applicationData.reviewData.levelNumber",
            null
           ]
          },
          "approvedAssignedQuestionsCount"
         ]
        },
        {
         "operator": "graphQL",
         "children": [
          "query reviewableQuestionsCount($appId: Int!) {\n  reviewableQuestionsCount(\n    appId: $appId\n  )\n}",
          "graphqlendpoint",
          [
           "appId"
          ],
          {
           "operator": "objectProperties",
           "children": [
            "applicationData.applicationId",
            null
           ]
          },
          "reviewableQuestionsCount"
         ]
        }
       ]
      }
     ]
    },
    {
     "operator": "=",
     "children": [
      {
       "operator": "objectProperties",
       "children": [
        "applicationData.reviewData.latestDecision.decision"
       ]
      },
      "NON_CONFORM"
     ]
    }
   ]
  },
  {
   "operator": "objectProperties",
   "children": [
    "applicationData.reviewData.isLastLevel"
   ]
  }
 ]
}
```

### CODE REVIEW

**Comment by CarlosNZ** [comment]
As I mentioned in the chat, you probably want to base this off #914 so we can keep the conflicts under control.

I'll have a look at the front-end expression later on and hopefully there's a way to simplify it.

**Comment by nmadruga** [comment]
> As I mentioned in the chat, you probably want to base this off #914 so we can keep the conflicts under control.
> 
> I'll have a look at the front-end expression later on and hopefully there's a way to simplify it.

Done!

Please note since this was originally based from `develop` it seems that PR #904 wasn't included in yours somehow, and it's showing on the diff here. Please ignore that - it should be ok when we are merging into `develop` or after you merge develop into #914 and then merge it here again. The only file which is actually changed in this PR is: database/buildSchema/50_views_functions_triggers.sql

**Comment by CarlosNZ** [comment]
> it seems that PR #904 wasn't included in yours somehow, and it's showing on the diff here

Okay, I'll re-merge the latest develop into mine, then you can remerge that into here, should get rid of this.

**Comment by CarlosNZ** [comment]
> Okay, I'll re-merge the latest develop into mine, then you can remerge that into here, should get rid of this.

Done -- you can update from `refactor-sql-functions-and-migration` now

**Pull request closed without merging**
