### PR TITLE
#38T Update NGINX Config to redirect traffic on HTTP requests

### PR DESCRIPTION
**Pull request by nmadruga**
Fixes https://github.com/openmsupply/conforma-templates/issues/38

Follow an advise to use this error_page 497 (for HTTP requests) to be redirected to the proper ssl url

### CODE REVIEW

**Review by CarlosNZ — APPROVED** [review]
Cool, thanks Nicole. 

Can I just confirm -- this is the exact file that is being used on the current demo server?

Also -- might be a good idea to add this to the other two config files:
- `docker/demo_server/nginx_config_single/default`
- `docker/nginx_config/conforma.conf`

**Comment by nmadruga** [comment]
> 

Interesting! I though about adding to the one in `demo_server/nginx_config_single` as well. But wondering why we have this third nginx_config... I'll have a look on the docs

**Comment by CarlosNZ** [comment]
> But wondering why we have this third nginx_config

I thought the generic one (in nginx_config) is the generic basis, whereas the two in "demo_server" are the actual implementations based off that (single and multiple variants)

**Comment by nmadruga** [comment]
> > But wondering why we have this third nginx_config
> 
> I thought the generic one (in nginx_config) is the generic basis, whereas the two in "demo_server" are the actual implementations based off that (single and multiple variants)

Found it! Is used when generating the docker - so it's a separated nginx configuration internal to docker.
I'll add the changes to `nginx_config_single`

**Pull request merged**
